In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [7]:
# Creating Arrays
print(np.array([1, 2, 3, 4, 5], dtype='float'))

[1. 2. 3. 4. 5.]


In [10]:
# Creating Multi-Dimensional Arrays
print(np.array([[1,2,3,4,5],[6,7,8,9,10]]))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
# Using Zeros & Ones
print(np.zeros(5))
print(np.zeros((2,3)))

print('---')
print(np.ones(5))
print(np.ones((2,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
---
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# Using random numbers
print(np.random.rand(2,3))

[[0.44809239 0.94462636 0.88708907]
 [0.18044156 0.20236124 0.77644903]]


In [16]:
# Array Of Your Choice
print(np.full((2,2),7))

[[7 7]
 [7 7]]


In [19]:
# Creating Matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Evenly Spaced Values
print(np.arange(5))
print(np.arange(5,10))
print(np.arange(1,10,2))

[0 1 2 3 4]
[5 6 7 8 9]
[1 3 5 7 9]


In [26]:
# Using Linspace (1-0/5-1=0.25 to find step size)
# np.linspace(start, stop, num)
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [33]:
# Calculate Dimension Size
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.ndim)

# Calculate values in rows and columns 
print(a.shape)
print('Rows = ',a.shape[0])
print('Columns = ',a.shape[1])

# Calculate size of array
print(a.size, 'or')
print(a.shape[0]*a.shape[1])

2
(2, 5)
Rows =  2
Columns =  5
10 or
10


In [34]:
# Reshaping ( for 1D to 2D )
print(np.arange(10).reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
# Flattening ( for 2D to 1D )
print(np.array([[1,2,3],[4,5,6]]).flatten())

# Ravel
print(np.array([[1,2,3],[4,5,6]]).ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [45]:
# Transponse ( makes rows to columns and columns to rows size )
print(np.array([[1,2,3],[4,5,6]]).transpose())
print('or')
print(np.array([[1,2,3],[4,5,6]]).T)


[[1 4]
 [2 5]
 [3 6]]
or
[[1 4]
 [2 5]
 [3 6]]


In [63]:
# Slicing  2D
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0]) # prints row 0
print(a[0,::2]) # prints row 0 with step size 2
print(a[0,2:5]) # prints row 0 column 2 to 5 arbitary values

print(a[1][1]) # prints row 1 column 1

[1 2 3 4 5]
[1 3 5]
7


In [64]:
# Slicing 1D
a = np.arange(10)
print(a[2:5]) # prints from 2 to 5

[2 3 4]


In [65]:
# Slicing 3D Array
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a[0]) # prints 0th array

[[1 2 3]
 [4 5 6]]


In [66]:
# Flip array
a = np.array([1,2,3,4,5])
print(np.flip(a))

[5 4 3 2 1]


In [67]:
# vstack & htsack
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b))) # rows increase
print(np.hstack((a,b))) # columns increase

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [71]:
# Concatenate for 2D
a = np.array([1,2,3]).reshape(1,3)
b = np.array([4,5,6]).reshape(1,3)
print(np.concatenate((a,b),axis=0)) # rows increase
print(np.concatenate((a,b),axis=1)) # columns increase

c = np.array([7,8,9])
d = np.array([10,11,12])

# for 1D
print(np.concatenate((c,d),axis=0)) # rows increase

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[ 7  8  9 10 11 12]


In [72]:
# Append
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.append(a,b))

[1 2 3 4 5 6]


In [6]:
# Operations
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array(a+b)
print(c)

[5 7 9]


1
