In [1]:
import numpy as np

In [2]:
# Write a program to Combine  a one and a two-dimensional NumPy Array

# Create a one-dimensional array
one_d_array = np.array([1, 2, 3])

# Create a two-dimensional array
two_d_array = np.array([[4, 5, 6], [7, 8, 9]])

# Reshape the one-dimensional array to have the same number of columns as the two-dimensional array
reshaped_one_d_array = one_d_array.reshape(1, -1)

# Combine the two arrays
combined_array = np.concatenate((reshaped_one_d_array, two_d_array), axis=0)

print(f"The combined array is:\n{combined_array}")


The combined array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?
# Create two numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Get the element-wise sum of a and b
c = np.add(a, b) # or c = a + b

print(f"The element-wise sum of a and b is:\n{c}")


The element-wise sum of a and b is:
[5 7 9]


In [4]:
# Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....
# Generate a sequence of numbers from 0 to 100 with gaps of 2
seq = np.arange(0, 101, 2)

print(f"The sequence is:\n{seq}")

The sequence is:
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [5]:
# Reverse a numpy array
# Create an array
arr = np.array([1, 2, 3, 4, 5])

print(f"The original array is:\n{arr}")

# Reverse the array
rev = arr[::-1]

print(f"The reversed array is:\n{rev}")

The original array is:
[1 2 3 4 5]
The reversed array is:
[5 4 3 2 1]


In [6]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
# Create an array
arr = np.array([1, 2, 0, 0, 4, 0])

print(f"The array is:\n{arr}")

# Find the indices of non-zero elements
ind = np.nonzero(arr)

print(f"The indices of non-zero elements are:\n{ind}")

The array is:
[1 2 0 0 4 0]
The indices of non-zero elements are:
(array([0, 1, 4], dtype=int64),)


In [7]:

# Create a 3x3 matrix with values ranging from 0 to 8
# Create a sequence of numbers from 0 to 8
seq = np.arange(9)

# Reshape the sequence into a 3x3 matrix
mat = np.reshape(seq, (3, 3))

print(f"The matrix is:\n{mat}")

The matrix is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Create a 10x10 array with random values

arr = np.random.rand(10, 10)

print(f"The array is:\n{arr}")


The array is:
[[0.85050947 0.52516072 0.45544646 0.52727105 0.79317676 0.49739829
  0.02822935 0.34820797 0.02016267 0.7085749 ]
 [0.00695014 0.98767847 0.40382327 0.23946753 0.30310529 0.64363882
  0.75442784 0.95222445 0.79609628 0.05857303]
 [0.87744223 0.56785395 0.57217907 0.70335518 0.31405875 0.5669238
  0.98177738 0.04181162 0.3897588  0.3181862 ]
 [0.33329417 0.49465009 0.36880389 0.06773782 0.89014353 0.94598239
  0.87383999 0.78465428 0.90146657 0.92204106]
 [0.84440391 0.22755357 0.94271219 0.03895695 0.98377881 0.73548815
  0.06568384 0.98079554 0.33774079 0.37281473]
 [0.12680719 0.19479854 0.44711743 0.43610525 0.75364837 0.62226723
  0.90683325 0.17267509 0.94538709 0.4912744 ]
 [0.31631095 0.52385362 0.05033465 0.55554263 0.62173165 0.07924272
  0.29446229 0.77519839 0.3791996  0.71908444]
 [0.19262596 0.54356563 0.05397026 0.38831383 0.45970934 0.3499822
  0.94526942 0.61114398 0.20576248 0.28697264]
 [0.26130569 0.34108683 0.10040028 0.15043728 0.61678608 0.83537466
